### PR TITLE
Resize Events in Month View and Resize Week/Day Events on Both Sides

### PR DESCRIPTION
**Pull request by arecvlohe**
## Description

This PR adds the ability to resize month events as well as resize week/day events on both ends, top and bottom. I wasn't able to get this to perform correctly on hover which I suppose is ideal.

Also it merges in master so the current branch is aligned with master.

### CODE REVIEW

**Comment by arecvlohe** [comment]
I am wondering how to merge this?

**Comment by arecvlohe** [comment]
Should I rebase the commits from master?

**Comment by jnmandal** [comment]
Went ahead and merged it. I'm pretty sure this is fine but if we see something weird we can go back and play around with rebasing

**Comment by arecvlohe** [comment]
Awesome, thanks @jnmandal!

**Pull request merged**
